version: "3.7"

services:
  node:
    image: "node:12"
    build: .
    ports:
      - "3000:3000"

  mongodb:
    image: "mongo:latest"
    environment:
        MONGO-INITDB_DATABASE: csap_db
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
        - 27017:27017
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: